spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: testtest
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
