spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booklib?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: testtest
  jpa:
    hibernate:
      ddl-auto: create

someParameter:
  value: 5463